// <auto-generated />
using System;
using EcoData.AquaTrack.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoData.AquaTrack.Database.Migrations
{
    [DbContext(typeof(AquaTrackDbContext))]
    partial class AquaTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean")
                        .HasColumnName("resolved");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<double?>("ThresholdMax")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_max");

                    b.Property<double?>("ThresholdMin")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold_min");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("TriggeredAt")
                        .HasDatabaseName("ix_alerts_triggered_at");

                    b.HasIndex("SensorId", "Resolved")
                        .HasDatabaseName("ix_alerts_sensor_id_resolved");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("api_key");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PullIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("pull_interval_seconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.IngestionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("data_source_id");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<DateTimeOffset>("LastRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recorded_at");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_logs");

                    b.HasIndex("DataSourceId", "IngestedAt")
                        .HasDatabaseName("ix_ingestion_logs_data_source_id_ingested_at");

                    b.ToTable("ingestion_logs", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parameter");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_readings");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_readings_recorded_at");

                    b.HasIndex("SensorId", "RecordedAt")
                        .HasDatabaseName("ix_readings_sensor_id_recorded_at");

                    b.HasIndex("SensorId", "Parameter", "RecordedAt")
                        .HasDatabaseName("ix_readings_sensor_id_parameter_recorded_at");

                    b.ToTable("readings", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Municipality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipality");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_sensors_source_id_external_id");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Alert", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Sensor", "Sensor")
                        .WithMany("Alerts")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.IngestionLog", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.DataSource", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_logs_data_sources_data_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Reading", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_readings_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Sensor", b =>
                {
                    b.HasOne("EcoData.AquaTrack.Database.Models.DataSource", "DataSource")
                        .WithMany("Sensors")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_data_sources_source_id");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.DataSource", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("EcoData.AquaTrack.Database.Models.Sensor", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
